[project]
name = "dishes64k"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kaggle>=1.7.4.5",
    "matplotlib>=3.10.7",
    "polars>=1.34.0",
    "spacy>=3.8.7",
]
